### ISSUE TITLE
MJPEG LiveView is broken

### ISSUE THREAD

**Issue by antonsviridenko** [bluecherrydvr/bluecherry-client#231]
Shows black screen when switching "Connection type:" from RTSP to MJPEG

**Comment by krieger-od** [comment]
Probably a server-side issue. For now, please ask customers to use RTSP mode, it is supposed to be used primarily.

I consider MJPEG mode in client app deprecated. It was needed in past time, when internal RTSP couldn't pass media from cameras which didn't have _their_ RTSP sources and exposed only MJPEG via HTTP. Now, Bluecherry server provides RTSP streams for cameras which have only MJPEG via HTTP streams.

**Comment by abelykh** [comment]
From the support perspective I think MJPEG should stay. RTSP produces a lot more issues, and is often not sufficiently reliable. Broken or malformed video from ip cameras may produce little effect on the recordings, but it often makes live viewing impossible or frustrating. 

Lower FPS without reconnect cycles or video smearing/frame loss is preferable IMO. It requires less support/maintenance, only uses one port and provides an alternative when RTSP is not an option.

I would, however advocate allowing users to switch MJPEG/RTSP on per-camera basis, instead of per-server basis.

**Comment by krieger-od** [comment]
@abelykh Bluecherry server provides MJPEG streams from the its own RTSP streams since July. Please see changes history for www/media/mjpeg.php.

**Comment by abelykh** [comment]
Sorry if I did not make myself clear - I was talking about mode of streaming to the client application. MJPEG definitely should not be considered depreciated and perhaps even given a higher priority for the reasons I've mentioned.

**Comment by krieger-od** [comment]
> I was talking about mode of streaming to the client application

Me too. www/media/mjpeg.php is also the source of stream for bc-client.

**Comment by tristam** [comment]
We actually use the mjpeg stream to the client for performance reasons.  There is so much motion in our environment, rtsp gets very laggy and choppy.

**Comment by krieger-od** [comment]
@tristam, ok, but there are alternatives to avoid lags and choppiness: you can switch to MJPEG mode at server web UI settings (no inter frames, so no artifacts if some frames don't get transmitted), or to configure H.264 stream settings to have less frames per second, less bandwidth used, or have key frames more often.

**Comment by antonsviridenko** [comment]
MJPEG stream generated by transcoding RTSP stream on server side by ffmpeg has different frame separator, client failed to parse such stream

Fixed in https://github.com/bluecherrydvr/bluecherry-client/commit/257e64a68584fda86fcfc203702213f3934aa81c
