### ISSUE TITLE
Documentation link broken in help menu

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-client#236]
https://secure.helpscout.net/conversation/102802822/5591/

http://help.bluecherrydvr.com/s/manuals/m/version2 is a dead URL, should point to http://docs.bluecherrydvr.com/collection/13-version-2-user-manual

**Comment by antonsviridenko** [comment]
Fixed in https://github.com/bluecherrydvr/bluecherry-client/commit/6b6741642a55060a9206ee1819e1ee6e753a6c69

But I've found that two other links in Help are broken too
"Bluecherry support" -> http://support.bluecherrydvr.com/tickets/new
"Suggest a feature" -> http://ideas.bluecherrydvr.com/

what should be the correct URLs for them?

**Comment by curtishall** [comment]
Bluecherry support - http://community.bluecherrydvr.com/topic/add
Suggest a feature - http://community.bluecherrydvr.com/topic/add

Both are the same link, I can't get a direct URL at the moment.

**Comment by antonsviridenko** [comment]
Updated URLs 
https://github.com/bluecherrydvr/bluecherry-client/commit/69f61455391bba4b5bcb0ce992a5b9f268256d4a
