### ISSUE TITLE
Implement thumbnail support

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-client#243]
Currently we save a JPEG file for each video event.  Customers have requested support for showing this image.  

I'm open for suggestions, but perhaps when a customer rolls over the event (either in the time line or browser) that the JPEG image is pulled and displayed.

**Comment by antonsviridenko** [comment]
> I'm open for suggestions, but perhaps when a customer rolls over the event (either in the time line or browser) that the JPEG image is pulled and displayed.

In a tool-tip like window?

I think it can take some time to download JPEG on each mouse appearing over event item in a list, this delay can be irritating for customers. Maybe it is better to download all JPEGs when events are requested?

**Comment by curtishall** [comment]
A tool-tip would work, we can cache JPEGs when events are downloading.  I think we should provide some type of notice to the user that a snapshot image is being downloaded, either in a progress bar or a spinning icon.

**Comment by antonsviridenko** [comment]
Thumbnail can be added to existing tooltips that appear on event records by adding HTML tag `<img src=path_to_thumbnail.jpg>` in text. However, looks like animated gifs do not work inside tooltip, so probably it is better to add text like "loading thumbnail..." instead of spinning icon
![thumbnail-example](https://cloud.githubusercontent.com/assets/2234049/14440785/a24f5958-0042-11e6-9445-a5ad100abd17.png)

**Comment by curtishall** [comment]
Awesome, will this be exposed for the timeline view as well?

**Comment by antonsviridenko** [comment]
Yes, it will, same tooltips are displayed on timeline widget
