### ISSUE TITLE
Consider switching to MPV as a player for recordings instead of Mplayer

### ISSUE THREAD

**Issue by antonsviridenko** [bluecherrydvr/bluecherry-client#290]
https://mpv.io/

**Comment by jasauders** [comment]
I can't help but to question the potential benefits in favor of MPV:

1) MPV's development is thriving. MPlayer's development on the other hand has tapered off quite a bit.

2) MPV can play back videos that are still "in progress". The current BC Client/MPlayer cannot, meaning folks have no form of instant replay. This is a critical feature with many folks/businesses.

3) In my limited testing, forcing hardware acceleration via --hwdec=vaapi flag works well in MPV, while I had trouble initializing it with other applications. Just a guess, but I wonder if it would be more straight forward to push hardware acceleration if MPV was the foundation. 

4) MPV has built in keyboard shortcuts for forward/reverse by 5 seconds or 60 seconds (via arrow keys in MPV), along with , and . for stepping forward/back by 1 frame. This granular control is far easier to work with as opposed to using the slider. The slider is a critical asset, but using the slider as the only means of seeking through video can be frustrating if you need to drill down to an exact frame within a recording.

5) While zoom functionality exists in the BC Client via the current MPlayer, it is a bit difficult to work with. Several controls are reversed. The zoom also gets reset to the center if I zoom, pan, and zoom again, making the act of zooming in feel a little clumsy, as it's not really expected behavior.

Assuming (as an end user I cannot confirm this) MPV can be somehow "dropped in place" of MPlayer *while* retaining full functionality that MPV provides, it stands to reason that MPV may address several bugs:

#285: being able to seek through in-progress video, basically allowing for a form of instant playback
#249: step video forward/back frame by frame via keys for very fine control (critical for some events)
#251: zoom controls backwards (perhaps easier to fix with MPV?)

Because of MPV's features, I find myself downloading the majority of Bluecherry's "videos of interest" strictly to run them through MPV to leverage the very features I spoke about above. They've become instrumental for my uses, and I'm sure there's others who may feel the same way. Having this functionality built in to the client itself would be great for Bluecherry users. 

If it serves any purpose I figured I'd share my ~/.config/mpv/input.conf contents. While the arrow keys (step forward/back 5/60 seconds) and , . keys (frame by frame) are default in MPV, the text below from input.conf adds zoom + pan functionality via the t, r, s, w, a, d, e keys.

t add video-zoom -0.25
r add video-zoom 0.25
s add video-pan-y -0.10
w add video-pan-y +0.10
a add video-pan-x +0.10
d add video-pan-x -0.10
e set video-pan-x 0; set video-pan-y 0; set video-zoom 0

It may also be worth sharing this: https://github.com/mpv-player/mpv/blob/master/DOCS/mplayer-changes.rst

All of the above is just from the perspective of an end user. I understand this proposal may not be as easy as turning on a light switch, though there doesn't seem to be a shortage of benefits unless there are technical details underneath that are beyond my level of understanding. 

As always, thanks for listening and all the hard work. :)

**Comment by antonsviridenko** [comment]
https://github.com/mpv-player/mpv/blob/master/libmpv/client.h

client API description
